//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsiazkaKucharska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jednostki
    {
        public Jednostki()
        {
            this.Przepisy_Skladniki = new HashSet<Przepisy_Skladniki>();
        }
    
        public int ID_JEDNOSTKI { get; set; }
        public string NAZWA { get; set; }
    
        public virtual ICollection<Przepisy_Skladniki> Przepisy_Skladniki { get; set; }
    }
}
