//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsiazkaKucharska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorie_Skladniki
    {
        public Kategorie_Skladniki()
        {
            this.Skladniki = new HashSet<Skladniki>();
        }
    
        public int S_ID_KATEGORII { get; set; }
        public string S_NAZWA { get; set; }
    
        public virtual ICollection<Skladniki> Skladniki { get; set; }
    }
}
