//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsiazkaKucharska.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KsiazkaKucharskaConnection : DbContext
    {
        public KsiazkaKucharskaConnection()
            : base("name=KsiazkaKucharskaConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Jednostki> Jednostki { get; set; }
        public DbSet<Kategorie_Przepisy> Kategorie_Przepisy { get; set; }
        public DbSet<Kategorie_Skladniki> Kategorie_Skladniki { get; set; }
        public DbSet<Przepisy> Przepisy { get; set; }
        public DbSet<Przepisy_Skladniki> Przepisy_Skladniki { get; set; }
        public DbSet<Skladniki> Skladniki { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
