//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsiazkaKucharska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przepisy_Skladniki
    {
        public int L_ID_PRZEPISU { get; set; }
        public int L_ID_SKLADNIKA { get; set; }
        public Nullable<double> ILOSC { get; set; }
        public Nullable<int> ID_JEDNOSTKI { get; set; }
    
        public virtual Jednostki Jednostki { get; set; }
        public virtual Przepisy Przepisy { get; set; }
        public virtual Skladniki Skladniki { get; set; }
    }
}
