//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsiazkaKucharska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przepisy
    {
        public Przepisy()
        {
            this.Przepisy_Skladniki = new HashSet<Przepisy_Skladniki>();
        }
    
        public int ID_PRZEPISU { get; set; }
        public string NAZWA { get; set; }
        public Nullable<int> ID_KATEGORII { get; set; }
        public string OPIS { get; set; }
        public string NOTATKI { get; set; }
        public Nullable<double> ILOSC_PORCJI { get; set; }
        public Nullable<int> CZAS_PRZYRZADZENIA { get; set; }
        public byte[] ZDJECIE { get; set; }
    
        public virtual Kategorie_Przepisy Kategorie_Przepisy { get; set; }
        public virtual ICollection<Przepisy_Skladniki> Przepisy_Skladniki { get; set; }
    }
}
