//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KsiazkaKucharska.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skladniki
    {
        public Skladniki()
        {
            this.Przepisy_Skladniki = new HashSet<Przepisy_Skladniki>();
        }
    
        public int ID_SKLADNIKA { get; set; }
        public string NAZWA { get; set; }
        public Nullable<int> ID_KATEGORII { get; set; }
        public string OPIS { get; set; }
        public string UWAGI { get; set; }
        public byte[] ZDJECIE { get; set; }
    
        public virtual Kategorie_Skladniki Kategorie_Skladniki { get; set; }
        public virtual ICollection<Przepisy_Skladniki> Przepisy_Skladniki { get; set; }
    }
}
